defmodule Quiz.GamesFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `Quiz.Games` context.
  """

  @doc """
  Generate a game. The join_code is auto-generated by the changeset.
  """
  def game_fixture(scope, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{status: :draft, title: "some title"})
    {:ok, game} = Quiz.Games.create_game(scope, attrs)
    game
  end

  @doc """
  Generate a single-choice question with two choices (A correct, B incorrect)
  unless `data` is overridden.
  """
  def question_fixture(scope, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{})
    game_id = Map.get_lazy(attrs, :game_id, fn -> game_fixture(scope).id end)

    defaults =
      case Map.get(attrs, :type, :single_choice) do
        :sequence ->
          %{
            type: :sequence,
            prompt: "some prompt",
            position: 42,
            data: %{items: [%{text: "First"}, %{text: "Second"}, %{text: "Third"}]}
          }

        :text_input ->
          %{
            type: :text_input,
            prompt: "some prompt",
            position: 42,
            data: %{solutions: [%{text: "Paris"}]}
          }

        :pin_on_image ->
          %{
            type: :pin_on_image,
            prompt: "some prompt",
            position: 42,
            data: %{
              pin: %{
                image_key: "uploads/test/fixture.png",
                target_x: 0.5,
                target_y: 0.5,
                radius: 0.1
              }
            }
          }

        :matching ->
          %{
            type: :matching,
            prompt: "some prompt",
            position: 42,
            data: %{
              pairs: [
                %{left_text: "France", right_text: "Paris"},
                %{left_text: "Japan", right_text: "Tokyo"},
                %{left_text: "Brazil", right_text: "Brasília"}
              ]
            }
          }

        _ ->
          %{
            type: :single_choice,
            prompt: "some prompt",
            position: 42,
            data: %{
              choices: [
                %{text: "A", correct: true},
                %{text: "B", correct: false}
              ]
            }
          }
      end

    attrs =
      attrs
      |> Map.put(:game_id, game_id)
      |> Enum.into(defaults)

    {:ok, question} = Quiz.Games.create_question(scope, attrs)
    question
  end
end
