defmodule Quiz.GamesFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `Quiz.Games` context.
  """

  @doc """
  Generate a game. The join_code is auto-generated by the changeset.
  """
  def game_fixture(scope, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{status: :draft, title: "some title"})
    {:ok, game} = Quiz.Games.create_game(scope, attrs)
    game
  end

  @doc """
  Generate a single-choice question with two choices (A correct, B incorrect)
  unless `data` is overridden.
  """
  def question_fixture(scope, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{})
    game_id = Map.get_lazy(attrs, :game_id, fn -> game_fixture(scope).id end)

    attrs =
      attrs
      |> Map.put(:game_id, game_id)
      |> Enum.into(%{
        type: :single_choice,
        prompt: "some prompt",
        position: 42,
        data: %{
          choices: [
            %{text: "A", correct: true},
            %{text: "B", correct: false}
          ]
        }
      })

    {:ok, question} = Quiz.Games.create_question(scope, attrs)
    question
  end
end
