defmodule Quiz.Games do
  @moduledoc """
  The Games context.
  """

  import Ecto.Query, warn: false
  alias Quiz.Repo

  alias Quiz.Games.Game
  alias Quiz.Accounts.Scope

  # How many times to regenerate a fresh join code when one collides on insert.
  @max_join_code_attempts 5

  @doc """
  Subscribes to scoped notifications about any game changes.

  The broadcasted messages match the pattern:

    * {:created, %Game{}}
    * {:updated, %Game{}}
    * {:deleted, %Game{}}

  """
  def subscribe_games(%Scope{} = scope) do
    key = scope.user.id

    Phoenix.PubSub.subscribe(Quiz.PubSub, "user:#{key}:games")
  end

  defp broadcast_game(%Scope{} = scope, message) do
    key = scope.user.id

    Phoenix.PubSub.broadcast(Quiz.PubSub, "user:#{key}:games", message)
  end

  @doc """
  Returns the list of games.

  ## Examples

      iex> list_games(scope)
      [%Game{}, ...]

  """
  def list_games(%Scope{} = scope) do
    Repo.all_by(Game, user_id: scope.user.id)
  end

  @doc """
  Gets a single game.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_game!(scope, 123)
      %Game{}

      iex> get_game!(scope, 456)
      ** (Ecto.NoResultsError)

  """
  def get_game!(%Scope{} = scope, id) do
    Repo.get_by!(Game, id: id, user_id: scope.user.id)
  end

  @doc """
  Creates a game.

  ## Examples

      iex> create_game(scope, %{field: value})
      {:ok, %Game{}}

      iex> create_game(scope, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_game(%Scope{} = scope, attrs) do
    with {:ok, game = %Game{}} <- insert_game(scope, attrs, @max_join_code_attempts) do
      broadcast_game(scope, {:created, game})
      {:ok, game}
    end
  end

  # The join code is randomly generated by `Game.changeset/3`, so a fresh
  # changeset each attempt yields a new code. On the rare unique collision we
  # rebuild and retry; any other error is returned as-is.
  defp insert_game(%Scope{} = scope, attrs, attempts) do
    case %Game{} |> Game.changeset(attrs, scope) |> Repo.insert() do
      {:error, %Ecto.Changeset{errors: errors}} = error ->
        if attempts > 1 and Keyword.has_key?(errors, :join_code),
          do: insert_game(scope, attrs, attempts - 1),
          else: error

      ok ->
        ok
    end
  end

  @doc """
  Updates a game.

  ## Examples

      iex> update_game(scope, game, %{field: new_value})
      {:ok, %Game{}}

      iex> update_game(scope, game, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_game(%Scope{} = scope, %Game{} = game, attrs) do
    true = game.user_id == scope.user.id

    with {:ok, game = %Game{}} <-
           game
           |> Game.changeset(attrs, scope)
           |> Repo.update() do
      broadcast_game(scope, {:updated, game})
      {:ok, game}
    end
  end

  @doc """
  Deletes a game.

  ## Examples

      iex> delete_game(scope, game)
      {:ok, %Game{}}

      iex> delete_game(scope, game)
      {:error, %Ecto.Changeset{}}

  """
  def delete_game(%Scope{} = scope, %Game{} = game) do
    true = game.user_id == scope.user.id

    with {:ok, game = %Game{}} <-
           Repo.delete(game) do
      broadcast_game(scope, {:deleted, game})
      {:ok, game}
    end
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking game changes.

  ## Examples

      iex> change_game(scope, game)
      %Ecto.Changeset{data: %Game{}}

  """
  def change_game(%Scope{} = scope, %Game{} = game, attrs \\ %{}) do
    true = game.user_id == scope.user.id

    Game.changeset(game, attrs, scope)
  end

  alias Quiz.Games.Question
  alias Quiz.Accounts.Scope

  @doc """
  Subscribes to scoped notifications about any question changes.

  The broadcasted messages match the pattern:

    * {:created, %Question{}}
    * {:updated, %Question{}}
    * {:deleted, %Question{}}

  """
  def subscribe_questions(%Scope{} = scope) do
    key = scope.user.id

    Phoenix.PubSub.subscribe(Quiz.PubSub, "user:#{key}:questions")
  end

  defp broadcast_question(%Scope{} = scope, message) do
    key = scope.user.id

    Phoenix.PubSub.broadcast(Quiz.PubSub, "user:#{key}:questions", message)
  end

  @doc """
  Returns the list of questions.

  ## Examples

      iex> list_questions(scope)
      [%Question{}, ...]

  """
  def list_questions(%Scope{} = scope) do
    Repo.all_by(Question, user_id: scope.user.id)
  end

  @doc """
  Returns the list of questions belonging to the given game, ordered by position.
  """
  def list_questions_for_game(%Scope{} = scope, %Game{} = game) do
    true = game.user_id == scope.user.id

    Question
    |> where([q], q.user_id == ^scope.user.id and q.game_id == ^game.id)
    |> order_by([q], asc: q.position)
    |> Repo.all()
  end

  @doc """
  Duplicates a game and all its questions into a fresh **draft** copy owned by
  the same user.

  Each question is copied with its prompt, description, position, media
  (image/video keys point at the same stored file — uploads are never deleted,
  so sharing keys is safe) and the full
  answer payload (`data`: choices, solutions, items, pairs, pin). Runtime and
  participant data is intentionally *not* copied — the copy starts a clean run,
  so there are no enrollments, submitted answers or corrections, the
  `current_position` is empty, `grading_published` is `false`, and a brand-new
  `join_code` is generated. The whole copy is atomic. Returns `{:ok, new_game}`.
  """
  def duplicate_game(%Scope{} = scope, %Game{} = game) do
    true = game.user_id == scope.user.id

    questions = list_questions_for_game(scope, game)

    Repo.transaction(fn ->
      {:ok, copy} =
        create_game(scope, %{
          title: game.title <> " (Kopie)",
          review_mode: game.review_mode,
          show_statistics: game.show_statistics
        })

      for question <- questions do
        Repo.insert!(%Question{
          type: question.type,
          prompt: question.prompt,
          description: question.description,
          position: question.position,
          data: question.data,
          media_image_key: question.media_image_key,
          media_video_key: question.media_video_key,
          game_id: copy.id,
          user_id: scope.user.id
        })
      end

      copy
    end)
  end

  @doc """
  Gets a single question.

  Raises `Ecto.NoResultsError` if the Question does not exist.

  ## Examples

      iex> get_question!(scope, 123)
      %Question{}

      iex> get_question!(scope, 456)
      ** (Ecto.NoResultsError)

  """
  def get_question!(%Scope{} = scope, id) do
    Repo.get_by!(Question, id: id, user_id: scope.user.id)
  end

  @doc """
  Creates a question.

  ## Examples

      iex> create_question(scope, %{field: value})
      {:ok, %Question{}}

      iex> create_question(scope, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_question(%Scope{} = scope, attrs) do
    changeset = Question.changeset(%Question{}, attrs, scope)

    with :ok <- ensure_questions_editable(scope, Ecto.Changeset.get_field(changeset, :game_id)),
         {:ok, question = %Question{}} <- Repo.insert(changeset) do
      broadcast_question(scope, {:created, question})
      {:ok, question}
    end
  end

  @doc """
  Creates a skeleton question of the given `type` with no prompt or answer data
  yet, appended after the game's existing questions.

  This backs the authoring UI's instant-create flow: picking a type persists the
  question immediately and drops the user into the edit form, where
  `update_question/3` enforces the full validation rules (prompt, answer data, …).
  """
  def create_question(%Scope{} = scope, %Game{} = game, type) do
    true = game.user_id == scope.user.id

    attrs = %{type: type, game_id: game.id, position: next_question_position(scope, game)}
    changeset = Question.create_changeset(%Question{}, attrs, scope)

    with :ok <- ensure_questions_editable(scope, game.id),
         {:ok, question = %Question{}} <- Repo.insert(changeset) do
      broadcast_question(scope, {:created, question})
      {:ok, question}
    end
  end

  defp next_question_position(%Scope{} = scope, %Game{} = game) do
    max =
      Question
      |> where([q], q.game_id == ^game.id and q.user_id == ^scope.user.id)
      |> select([q], max(q.position))
      |> Repo.one()

    (max || 0) + 1
  end

  @doc """
  Updates a question.

  ## Examples

      iex> update_question(scope, question, %{field: new_value})
      {:ok, %Question{}}

      iex> update_question(scope, question, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_question(%Scope{} = scope, %Question{} = question, attrs) do
    true = question.user_id == scope.user.id

    with {:ok, game} <- fetch_editable_game(scope, question.game_id),
         {:ok, question = %Question{}} <-
           question
           |> Question.changeset(attrs, scope, authoring_mode(game))
           |> Repo.update() do
      broadcast_question(scope, {:updated, question})
      {:ok, question}
    end
  end

  @doc """
  Deletes a question.

  ## Examples

      iex> delete_question(scope, question)
      {:ok, %Question{}}

      iex> delete_question(scope, question)
      {:error, %Ecto.Changeset{}}

  """
  def delete_question(%Scope{} = scope, %Question{} = question) do
    true = question.user_id == scope.user.id

    with :ok <- ensure_questions_editable(scope, question.game_id),
         {:ok, question = %Question{}} <-
           Repo.delete(question) do
      broadcast_question(scope, {:deleted, question})
      {:ok, question}
    end
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking question changes.

  ## Examples

      iex> change_question(scope, question)
      %Ecto.Changeset{data: %Question{}}

  """
  def change_question(%Scope{} = scope, %Question{} = question, attrs \\ %{}) do
    true = question.user_id == scope.user.id

    Question.changeset(question, attrs, scope, question_authoring_mode(scope, question.game_id))
  end

  @doc """
  Rewrites the `:position` of each question in `ordered_ids` so that positions
  match the given order (1-based). All ids must belong to the given game and
  the scope's user, otherwise the function returns `{:error, :invalid}` and no
  changes are persisted.
  """
  def reposition_questions(%Scope{} = scope, %Game{} = game, ordered_ids)
      when is_list(ordered_ids) do
    true = game.user_id == scope.user.id

    with :ok <- ensure_questions_editable(scope, game.id) do
      do_reposition_questions(scope, game, ordered_ids)
    end
  end

  defp do_reposition_questions(%Scope{} = scope, %Game{} = game, ordered_ids) do
    questions =
      Question
      |> where([q], q.game_id == ^game.id and q.user_id == ^scope.user.id)
      |> Repo.all()

    existing_ids = MapSet.new(questions, & &1.id)
    given_ids = Enum.map(ordered_ids, &normalize_id/1)

    cond do
      Enum.any?(given_ids, &is_nil/1) ->
        {:error, :invalid}

      MapSet.new(given_ids) != existing_ids ->
        {:error, :invalid}

      length(given_ids) != length(Enum.uniq(given_ids)) ->
        {:error, :invalid}

      true ->
        multi =
          given_ids
          |> Enum.with_index(1)
          |> Enum.reduce(Ecto.Multi.new(), fn {id, pos}, multi ->
            Ecto.Multi.update_all(
              multi,
              {:pos, id},
              from(q in Question, where: q.id == ^id),
              set: [position: pos]
            )
          end)

        case Repo.transaction(multi) do
          {:ok, _} ->
            broadcast_question(scope, {:reordered, game})
            :ok

          {:error, _, _, _} ->
            {:error, :invalid}
        end
    end
  end

  # Run states in which question authoring is frozen. Stored answers and grades
  # were computed against the questions as they existed during the run, so
  # adding, removing, reordering, or editing a question afterwards would
  # silently invalidate the leaderboard and corrections (grading is one-shot at
  # submission time and never recomputed). A `:closed` run can be reopened to
  # `:open`, which re-enables editing.
  @locked_run_states [:finished, :closed]

  @doc """
  Returns `true` when a game's run is in a state where its questions must not
  be edited (currently `:finished` or `:closed`). Useful for hiding authoring
  controls in the UI; the context functions enforce this regardless.
  """
  def questions_locked?(%Game{status: status}), do: status in @locked_run_states

  @doc """
  The validation strictness for authoring questions in `game`.

  A `:draft` quiz is still being built, so questions are validated leniently
  (`:draft`); once a quiz has been opened its questions are live and must stay
  complete, so edits are validated strictly (`:publish`). See
  `Quiz.Games.Question.changeset/4`.
  """
  def authoring_mode(%Game{status: :draft}), do: :draft
  def authoring_mode(%Game{}), do: :publish
  # An unloadable game (should not happen for a persisted question) errs strict.
  def authoring_mode(nil), do: :publish

  @doc """
  Questions in `game` that do not yet meet the `:publish` bar (see
  `Quiz.Games.Question.ready?/1`), ordered by position. Empty means the quiz is
  ready to open. Used by `Quiz.Play.open_run/2` to gate the `draft -> open`
  transition so a live quiz never contains an unplayable question.
  """
  def incomplete_questions(%Scope{} = scope, %Game{} = game) do
    scope
    |> list_questions_for_game(game)
    |> Enum.reject(&Question.ready?/1)
  end

  # Loads the owning game and rejects question mutations when its run is locked.
  defp ensure_questions_editable(scope, game_id) do
    case fetch_editable_game(scope, game_id) do
      {:ok, _game} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  # Loads the owning game, returning `{:error, :run_locked}` when its run is in a
  # state that freezes authoring. A missing/foreign game yields `{:ok, nil}` so
  # callers keep their prior lenient behaviour (the scope check upstream owns
  # ownership enforcement).
  defp fetch_editable_game(%Scope{} = scope, game_id) when not is_nil(game_id) do
    case Repo.get_by(Game, id: game_id, user_id: scope.user.id) do
      %Game{status: status} when status in @locked_run_states -> {:error, :run_locked}
      %Game{} = game -> {:ok, game}
      nil -> {:ok, nil}
    end
  end

  defp fetch_editable_game(_scope, _game_id), do: {:ok, nil}

  # Reads just the owning game's status to pick the authoring validation mode,
  # without loading the whole record (called on every keystroke via the form).
  defp question_authoring_mode(%Scope{} = scope, game_id) when not is_nil(game_id) do
    Game
    |> where([g], g.id == ^game_id and g.user_id == ^scope.user.id)
    |> select([g], g.status)
    |> Repo.one()
    |> case do
      :draft -> :draft
      _ -> :publish
    end
  end

  defp question_authoring_mode(_scope, _game_id), do: :publish

  defp normalize_id(id) when is_integer(id), do: id

  defp normalize_id(id) when is_binary(id) do
    case Integer.parse(id) do
      {n, ""} -> n
      _ -> nil
    end
  end

  defp normalize_id(_), do: nil
end
